site_name: 'Отчет по первой лабораторной'

theme:
  name: material

nav:
  - Lab_1:
      - 'Home': 'lab_1.md'
      - 'Task_1': 'task_1.md'
      - 'Task_2': 'task_2.md'
      - 'Task_3': 'task_3.md'
      - 'Task_4': 'task_4.md'
      - 'Task_5': 'task_5.md'
  - Lab_2:
      - 'Home': 'lab_2.md'
      - 'Users App':
          - 'Overview':
              - 'Data Models': 'users/models/overview.md'
              - 'Controllers': 'users/views/overview.md'
              - 'Routers': 'users/urls/overview.md'
          - 'Data Models Details':
              - 'User': 'users/models/user.md'
          - 'Controllers Details':
              - 'User Views': 'users/views/user_views.md'
          - 'Screenshots': 'users/screenshots/user_screens.md'
      - 'Flights App':
          - 'Overview':
              - 'Data Models': 'flights/models/overview.md'
              - 'Controllers': 'flights/views/overview.md'
              - 'Routers': 'flights/urls/overview.md'
          - 'Data Models Details':
              - 'Airplane': 'flights/models/airplane.md'
              - 'Airline': 'flights/models/airline.md'
              - 'Flight': 'flights/models/flight.md'
              - 'Ticket': 'flights/models/ticket.md'
              - 'Reservation': 'flights/models/reservation.md'
              - 'Review': 'flights/models/review.md'
          - 'Controllers Details':
              - 'Flight Views': 'flights/views/flight_views.md'
          - 'Screenshots': 'flights/screenshots/flight_screens.md'
  - Lab_3:
      - Home: lab_3.md
      - Lab_3.1:
          - Практическое задание №1: prac_1.md
          - Практическое задание №2: prac_2.md
          - Практическое задание №3: prac_3.md
      - Lab_3:
          - Alpinists: alpinists.md
          - Guides: guides.md
          - Mountains: mountains.md
          - Routes: routes.md
          - Clubs: clubs.md
          - Climbs: climbs.md
          - Groups: groups.md
          - Group Members: group_members.md
  - Lab_4:
      - Home: lab_4.md
      - Router: router.md
      - VueX Store: vuex.md
      - Api Config: api.md
      - Components:
          - SiteNavbar: SiteNavbar.md
          - HomePage: HomePage.md
          - LoginModal: LoginModal.md
          - RegisterModal: RegisterModal.md
          - ClubsTable: ClubsTable.md
          - RoutesTable: RoutesTable.md
          - MountDetail: MountDetail.md

